### ISSUE TITLE
Error: Cannot find ffprobe

### ISSUE THREAD

**Issue by owalida** [charlypoirier/redditube#10]
Hello,
I have this error 
```
Error: Cannot find ffprobe
    at C:\Users\User\node_modules\fluent-ffmpeg\lib\ffprobe.js:145:31
    at C:\Users\User\node_modules\fluent-ffmpeg\lib\capabilities.js:194:9
    at wrapper (C:\Users\User\node_modules\async\dist\async.js:271:20)
    at next (C:\Users\User\node_modules\async\dist\async.js:5762:24)
    at C:\Users\User\node_modules\async\dist\async.js:324:20
    at C:\Users\User\node_modules\fluent-ffmpeg\lib\capabilities.js:183:15
    at suppressedCallback (fs.js:236:5)
    at FSReqCallback.oncomplete (fs.js:180:23)
Emitted 'error' event on FfmpegCommand instance at:
    at C:\Users\User\node_modules\fluent-ffmpeg\lib\recipes.js:430:21
    at handleCallback (C:\Users\User\node_modules\fluent-ffmpeg\lib\ffprobe.js:106:9)
    at C:\Users\User\node_modules\fluent-ffmpeg\lib\ffprobe.js:145:16
    at C:\Users\User\node_modules\fluent-ffmpeg\lib\capabilities.js:194:9
    [... lines matching original stack trace ...]
    at FSReqCallback.oncomplete (fs.js:180:23)

```
FFmpeg is installed successfully and I checheck and I do have the files on these path

Do you know what is causing this issue please ?

Thank you very much

**Comment by charlypoirier** [comment]
Hello,

Sorry for replying this late, I don't know what could be causing this issue.
Let me know if you still need help resolving this.
